import {test} from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import {PGlite} from "@electric-sql/pglite";
let owner="11111111-1111-4111-8111-111111111111",staff="22222222-2222-4222-8222-222222222222",
 card="33333333-3333-4333-8333-333333333333",inv="44444444-4444-4444-8444-444444444444",
 token="a".repeat(64),session="c".repeat(64);
test("invitations preserve issuance, distinguish views from verified access and enforce patient-scoped imports and revocation", async()=>{
 const db=new PGlite();
 try {
  await db.exec("create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key);create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);");
  for(const file of fs.readdirSync("supabase/migrations").filter(file=>file.endsWith(".sql")).sort()) await db.exec(fs.readFileSync("supabase/migrations/"+file,"utf8"));
  await db.query("insert into public.clinic_staff(id,email,role,status) values($1,'secretary@example.test','secretary','active')",[staff]);
  owner=(await db.query("select id from public.clinic_staff where email='galadv73@gmail.com'")).rows[0].id;
  const appointment={id:card,patient_label:"Fictional invitation",appointment_at:null,pin_digest:"correct",expires_at:new Date(Date.now()+7*86400000).toISOString()};
  const link={id:inv,token_hash:token,language:"en",secret_ciphertext:"x".repeat(60)};
  await db.query("select public.issue_invitation($1,$2,$3,false)",[staff,JSON.stringify(appointment),JSON.stringify(link)]);
  let row=(await db.query("select * from public.invitation_links where id=$1",[inv])).rows[0];
  assert.equal(row.issuer_label,"secretary@example.test");assert.equal(row.first_verified_at,null);assert.equal(row.clalit_connected_at,null);
  await db.query("select public.record_invitation_view($1)",[token]);
  row=(await db.query("select * from public.invitation_links where id=$1",[inv])).rows[0];
  assert.ok(row.first_viewed_at);assert.equal(row.first_verified_at,null);
  assert.equal((await db.query("select public.verify_patient_pin($1,'wrong',$2) as ok",[token,session])).rows[0].ok,false);
  assert.equal((await db.query("select public.verify_patient_pin($1,'correct',$2) as ok",[token,session])).rows[0].ok,true);
  row=(await db.query("select * from public.invitation_links where id=$1",[inv])).rows[0];
  assert.ok(row.first_verified_at);assert.equal(row.clalit_connected_at,null);
  await assert.rejects(db.query("select public.create_patient_import_grant($1,$2,false)",[session,"d".repeat(64)]),/consent/);
  await assert.rejects(db.query("select public.create_patient_import_grant('foreign',$1,true)",["d".repeat(64)]),/patient access/);
  await db.query("select public.create_patient_import_grant($1,$2,true)",[session,"d".repeat(64)]);
  assert.equal((await db.query("select clalit_connected_at from public.invitation_links where id=$1",[inv])).rows[0].clalit_connected_at,null,"A connection button/grant does not establish Clalit access");
  const bundle={provider:"clalit",subject_scope:"self",schema_version:1,records:[{id:"99999999-9999-4999-8999-999999999999",entries:[]}],coverage:[]};
  const accepted=(await db.query("select public.accept_medical_import($1,$2,$3) as value",["d".repeat(64),"e".repeat(64),JSON.stringify(bundle)])).rows[0].value;
  row=(await db.query("select * from public.invitation_links where id=$1",[inv])).rows[0];
  assert.ok(row.clalit_connected_at);assert.equal(row.latest_import_at,null);
  const lease="66666666-6666-4666-8666-666666666666";
  assert.equal((await db.query("select public.claim_medical_summary($1,$2,$3) as ok",[accepted.id,owner,lease])).rows[0].ok,true);
  await db.query("select public.manage_invitation($1,$2,'revoke',null)",[staff,inv]);
  assert.equal((await db.query("select public.finish_medical_summary($1,$2,'{}','claude-fictional-test','{}') as ok",[accepted.id,lease])).rows[0].ok,false);
  assert.equal((await db.query("select latest_import_at from public.invitation_links where id=$1",[inv])).rows[0].latest_import_at,null);
  assert.equal((await db.query("select count(*)::int as n from public.portal_sessions where appointment_id=$1",[card])).rows[0].n,0);
  assert.equal((await db.query("select public.manage_invitation($1,$2,'extend',now()+interval '20 days') as ok",[staff,inv])).rows[0].ok,false);
  const nextLink={...link,id:"77777777-7777-4777-8777-777777777777",token_hash:"f".repeat(64)};
  await db.query("select public.issue_invitation($1,$2,$3,true)",[staff,JSON.stringify(appointment),JSON.stringify(nextLink)]);
  assert.equal((await db.query("select count(*)::int as n from public.invitation_links where appointment_id=$1",[card])).rows[0].n,2);
  assert.equal((await db.query("select public.verify_patient_pin($1,'correct',$2) as ok",[token,"1".repeat(64)])).rows[0].ok,false);
  await db.query("select public.manage_invitation($1,$2,'delete',null)",[staff,nextLink.id]);
  assert.equal((await db.query("select count(*)::int as n from public.appointments where id=$1",[card])).rows[0].n,1,"Deleting an invitation does not delete clinical records");
  const listed=(await db.query("select public.list_invitation_links($1,'','all','all',true,0,50) as data",[staff])).rows[0].data;
  assert.equal(listed.total,2);assert.ok(listed.items.some(item=>item.status==="deleted"));
  assert.equal(Object.hasOwn(listed.items[0],"secret_ciphertext"),false);
  assert.equal((await db.query("select public.list_invitation_links($1,'','active','all',false,0,50) as data",[staff])).rows[0].data.total,0);
  const card2="88888888-8888-4888-8888-888888888888",inv2="88888888-8888-4888-8888-888888888887",session2="2".repeat(64),token2="3".repeat(64),grant2="4".repeat(64);
  await db.query("select public.issue_invitation($1,$2,$3,false)",[staff,JSON.stringify({...appointment,id:card2,patient_label:"Successful import fixture"}),JSON.stringify({...link,id:inv2,token_hash:token2})]);
  await db.query("select public.verify_patient_pin($1,'correct',$2)",[token2,session2]);
  await db.query("select public.create_patient_import_grant($1,$2,true)",[session2,grant2]);
  const imported2=(await db.query("select public.accept_medical_import($1,$2,$3) as value",[grant2,"5".repeat(64),JSON.stringify(bundle)])).rows[0].value;
  await db.query("select public.claim_medical_summary($1,$2,$3)",[imported2.id,owner,lease]);
  assert.equal((await db.query("select public.finish_medical_summary($1,$2,'{}','claude-fictional-test',$3) as ok",[imported2.id,lease,JSON.stringify(bundle)])).rows[0].ok,true);
  assert.ok((await db.query("select latest_import_at from public.invitation_links where id=$1",[inv2])).rows[0].latest_import_at);
  const sending="99999999-9999-4999-8999-999999999991";
  await db.query("select public.reserve_invitation_send($1,$2,$3,'fictional@example.test')",[staff,inv2,sending]);
  assert.equal((await db.query("select last_sent_at from public.invitation_links where id=$1",[inv2])).rows[0].last_sent_at,null);
  await db.query("select public.finish_invitation_send($1,$2,'accepted','fictional-provider-id')",[staff,sending]);
  assert.ok((await db.query("select last_sent_at from public.invitation_links where id=$1",[inv2])).rows[0].last_sent_at);
  assert.equal((await db.query("select public.reserve_invitation_send($1,$2,$3,'fictional@example.test') as v",[staff,inv2,sending])).rows[0].v.status,"accepted");
  await assert.rejects(db.query("select public.reserve_invitation_send($1,$2,$3,'fictional@example.test')",[staff,inv2,lease]),/rate limit/);
  const card3="aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",inv3="bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",token3="6".repeat(64);
  await db.query("select public.issue_invitation($1,$2,$3,false)",[staff,JSON.stringify({...appointment,id:card3,patient_label:"Upload fixture"}),JSON.stringify({...link,id:inv3,token_hash:token3})]);
  const doc={id:"cccccccc-cccc-4ccc-8ccc-cccccccccccc",appointment_id:card3,filename:"fictional.pdf",storage_path:"fictional/document.pdf",sha256:"7".repeat(64),bytes:10,created_at:new Date().toISOString()};
  await db.query("select public.attach_document($1)",[JSON.stringify(doc)]);
  const uploads=(await db.query("select public.list_invitation_links($1,'Upload fixture','all','all',false,0,50) as v",[staff])).rows[0].v.items[0];
  assert.equal(uploads.patient_upload_count,1);assert.ok(uploads.latest_upload_at);assert.equal(uploads.import_status,"not_started");
  await db.query("delete from public.clinic_staff where id=$1",[staff]);
  assert.equal((await db.query("select issuer_label from public.invitation_links where id=$1",[inv2])).rows[0].issuer_label,"secretary@example.test");
  await db.exec("set role anon");
  await assert.rejects(db.query("select * from public.invitation_links"),/permission/);
  await assert.rejects(db.query("select public.record_invitation_view($1)",[token]),/permission/);
 } finally {await db.close();}
});